version: '3'
services:
  db:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      TZ: Asia/Tokyo
    networks:
      - default
    volumes:
      - pg-data:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - default
    volumes:
      - .:/ketsuatsu_app:cached
      # exclude volumes
      - /ketsuatsu_app/tmp
      - /ketsuatsu_app/log
      - /ketsuatsu_app/.git
      - vendor_bundle:/ketsuatsu_app/vendor/bundle
      - vendor_assets:/ketsuatsu_app/vendor/assets
      - node_modules:/ketsuatsu_app/node_modules
    tty: true
    stdin_open: true
    command: ash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
volumes:
  pg-data:
  vendor_bundle:
  vendor_assets:
  node_modules:
